services:
  redis:
    container_name: ubi-redis
    image: redis:7.0.6
    platform: linux/amd64
    ports:
      - "16379:6379"
    volumes:
      - $CP_PATH/store_data:/data
      - $CP_PATH/store_data/conf:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf

  resource-exporter:
    container_name: resource-exporter
    image: filswan/hardware-exporter:v1.0

